# Generated by Django 4.0.2 on 2023-05-03 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('travel_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('departure_date', 'Departure date'), ('arrival_date', 'Arrival date')], default='departure_date', max_length=20)),
            ],
        ),
    ]
